server:
  port: ${PORT:8080}

spring:
  application:
    name: studyworld
  datasource:
    # Use Railway-provided PG* variables directly
    url: jdbc:postgresql://${PGHOST}:${PGPORT:5432}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:studiwelt.team@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:tfld igvv vmse vecb}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  frontend-url: ${APP_FRONTEND_URL:http://localhost:4200}
  jwt:
    issuer: ${APP_JWT_ISSUER:studyworld}
    secret: ${APP_JWT_SECRET:b2PqBQh8FnN6j/nUt4Aem5XRABdg9J4y7bKFAgRnTp1R7Y4UbdFZcfK4EvjKkkYbQfdP0SE0Im77jGItWdBOeg==}
    access-token-ttl: ${APP_JWT_ACCESS_TTL:PT15M}
    refresh-token-ttl: ${APP_JWT_REFRESH_TTL:P7D}
    mfa-token-ttl: ${APP_JWT_MFA_TTL:PT5M}
  mfa:
    issuer: ${APP_MFA_ISSUER:StudyWorld}
    qr-width: ${APP_MFA_QR_WIDTH:300}
    qr-height: ${APP_MFA_QR_HEIGHT:300}
  security:
    max-failed-attempts: ${APP_SECURITY_MAX_FAILED:6}
    lockout-duration: ${APP_SECURITY_LOCKOUT:PT15M}
    password-expiry: ${APP_SECURITY_PASSWORD_EXPIRY:P90D}
  verification:
    token-ttl: ${APP_VERIFICATION_TTL:PT24H}
  password-reset:
    token-ttl: ${APP_PASSWORD_RESET_TTL:PT1H}
