server:
  port: ${PORT:8080}

spring:
  application:
    name: studyworld
  datasource:
    # Use Railway-provided PG* variables directly
    url: jdbc:postgresql://${PGHOST}:${PGPORT:5432}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never

app:
  # Set your public frontend origin (prod). No Railway default for safety.
  frontend-url: ${APP_FRONTEND_URL:https://studiwelt.com}
  mail:
    from-email: ${APP_MAIL_FROM:support@studiwelt.com}
    from-name: ${APP_MAIL_FROM_NAME:StudyWorld}
    resend:
      api-key: ${APP_RESEND_API_KEY:re_c4FJD24D_F6E6i9zpBKa9Dhxm2ZhBGiVb}
  jwt:
    issuer: ${APP_JWT_ISSUER:studyworld}
    secret: ${APP_JWT_SECRET:b2PqBQh8FnN6j/nUt4Aem5XRABdg9J4y7bKFAgRnTp1R7Y4UbdFZcfK4EvjKkkYbQfdP0SE0Im77jGItWdBOeg==}
    access-token-ttl: ${APP_JWT_ACCESS_TTL:PT15M}
    refresh-token-ttl: ${APP_JWT_REFRESH_TTL:P7D}
    mfa-token-ttl: ${APP_JWT_MFA_TTL:PT5M}
  mfa:
    issuer: ${APP_MFA_ISSUER:StudiWelt}
    qr-width: ${APP_MFA_QR_WIDTH:300}
    qr-height: ${APP_MFA_QR_HEIGHT:300}
  security:
    max-failed-attempts: ${APP_SECURITY_MAX_FAILED:6}
    lockout-duration: ${APP_SECURITY_LOCKOUT:PT15M}
    password-expiry: ${APP_SECURITY_PASSWORD_EXPIRY:P90D}
  verification:
    token-ttl: ${APP_VERIFICATION_TTL:PT1H}
  password-reset:
    token-ttl: ${APP_PASSWORD_RESET_TTL:PT30M}
